const ADD_PRODUCT = 'ADD_PRODUCT'
const INCREASE_QUANTITY_OF_PRODUCT = 'INCREASE_AMOUNT_OF_PRODUCT'
const DECREASE_QUANTITY_OF_PRODUCT = 'DECREASE_AMOUNT_OF_PRODUCT'

export default {
    ADD_PRODUCT,
    INCREASE_QUANTITY_OF_PRODUCT,
    DECREASE_QUANTITY_OF_PRODUCT,
}